.github/workflows/automerge.yml
- Updated actors for autoapprove
See https://github.com/asyncapi/asyncapi-node/pull/20#issuecomment-705646435
=> chore: Cleaned up automerge workflow for dependabot

package.json, schemas/2.0.0.json
Replica of https://github.com/asyncapi/asyncapi/pull/493
Resolves https://github.com/asyncapi/asyncapi/issues/492
=> fix: change minItems of oneOf and anyOf to 1

.github/workflows/if-nodejs-release.yml, .github/workflows/if-nodejs-version-bump.yml, package-lock.json, package.json
we need changes in release pipeline there in release branch
=> chore: update release branch with latest master

schemas/2.0.0.json, schemas/2.1.0.json
initial PR from Laurent was done against 2.0 and not 2.1 schema.
=> fix: move changes in message examples to 2.1 schema

schemas/2.1.0.json
As in title. Move changes from https://github.com/asyncapi/asyncapi-node/pull/63 to release branch
=> chore: support Boolean schemas

README.md
Found a readME referencing an old website of Fran's that's no longer actively maintained by him since he's lost the domain to a Chinese website :D
=> chore: remove Fran's old website that's no longer active

schemas/2.1.0.json
Refs https://github.com/asyncapi/spec/issues/604
Refs https://github.com/asyncapi/spec/pull/608
=> fix: fix Message Trait examples field

index.js, package.json, schemas/2.3.0.json
- create new version of json schema
- update release branch name in package.json
Contributes to: asyncapi/spec#675
Signed-off-by: Dale Lane <dale.lane@uk.ibm.com>
=> chore: update release branch

index.js, package-lock.json, package.json, schemas/2.0.0-rc1.json, schemas/2.0.0-rc2.json, schemas/2.0.0.json, schemas/2.1.0.json, schemas/2.2.0.json, schemas/2.3.0.json
This PR is created upfront to reflect on a daily basis what things are included in the release.
Also, the reason to create this PR a long time before the release is to enable automation (bot keeps upstream branches always up to date with master) that we have in place to regularly update the release branch with whatever is changed in the master branch. So nobody has to do it manually.
=> feat: release for version 2.3.0 of the spec

index.js, schemas/2.4.0.json
Part of https://github.com/asyncapi/spec/issues/735
=> chore: update 2022-04-release branch

.github/workflows/automerge.yml, .github/workflows/autoupdate.yml, .github/workflows/bump.yml, .github/workflows/if-go-pr-testing.yml, .github/workflows/if-nodejs-pr-testing.yml, .github/workflows/if-nodejs-release.yml, .github/workflows/if-nodejs-version-bump.yml, .github/workflows/issues-prs-notifications.yml, .github/workflows/lint-pr-title.yml, .github/workflows/notify-tsc-members-mention.yml, .github/workflows/release-announcements.yml, .github/workflows/sentiment-analysis.yml, .github/workflows/stale-issues-prs.yml, .github/workflows/welcome-first-time-contrib.yml, CODEOWNERS
This PR merges the branch with the latest master.
=> refactor: add update with master

index.js, package.json, schemas/2.4.0.json
https://github.com/asyncapi/spec/issues/735
=> chore: update 2022-04-release branch with master changes

package.json
This PR merged master into next-major for https://github.com/asyncapi/spec-json-schemas/pull/184 to have no conflicts.
=> refactor: update with master

migrations/Migrate to version 3.md
This PR improves the migration information to be more in-depth about which problems might arise when migrating.
=> docs: improve migration information

package.json, scripts/add-new-version.js
This PR simplifies the script that creates new versions for better maintainability.
=> chore: add separate script for creating new versions

README.md
This PR adds 2 required manual steps for creating new versions.
=> docs: add 2 manual steps for creating new versions

CODEOWNERS
https://github.com/asyncapi/spec/issues/844
https://github.com/asyncapi/spec/issues/845
=> chore: add Sergio and Vladimir as code owners

bindings/ibmmq/0.1.0/channel.json, bindings/kafka/0.4.0/channel.json, bindings/kafka/0.4.0/message.json, bindings/kafka/0.4.0/operation.json, bindings/kafka/0.4.0/server.json, bindings/mqtt5/0.2.0/server.json
Adds some missing changes that were missed from the binding repository.
=> feat: add kafka 0.4 and mqtt5 changes

.github/workflows/if-nodejs-pr-testing.yml, .github/workflows/welcome-first-time-contrib.yml, definitions/2.0.0-rc1/message.json, definitions/2.0.0-rc1/operation.json, definitions/2.0.0-rc2/message.json, definitions/2.0.0-rc2/operation.json, definitions/2.0.0/message.json, definitions/2.0.0/operation.json, definitions/2.1.0/message.json, definitions/2.1.0/operation.json, definitions/2.2.0/message.json, definitions/2.2.0/operation.json, definitions/2.3.0/message.json, definitions/2.3.0/operation.json, definitions/2.4.0/message.json, definitions/2.4.0/operation.json, definitions/2.5.0/message.json, definitions/2.5.0/operation.json, definitions/2.6.0/message.json, definitions/2.6.0/operation.json, schemas/2.0.0-rc1.json, schemas/2.0.0-rc2.json, schemas/2.0.0.json, schemas/2.1.0.json, schemas/2.2.0.json, schemas/2.3.0.json, schemas/2.4.0.json, schemas/2.5.0.json, schemas/2.6.0.json
This PR updates `next-major-spec` with master.
=> feat: update with master

definitions/3.0.0/operationTrait.json
OperationTrait.json has been successfully updated by mentioning the message inside the object description as being excluded
fixes #994
=> docs: update operationTrait.json

definitions/3.0.0/operationBindingsObject.json
The latest http binding version is `0.3.0`
=> fix: http operation bindings not using latest version

definitions/3.0.0/channelBindingsObject.json, definitions/3.0.0/messageBindingsObject.json, definitions/3.0.0/operationBindingsObject.json, definitions/3.0.0/serverBindingsObject.json
cf. spotted in a comment in
https://github.com/asyncapi/spec-json-schemas/pull/481
=> fix: kafka bindings not using latest version

CODEOWNERS
As discussed in https://github.com/asyncapi/spec-json-schemas/issues/513#issuecomment-2060839618 I want to help maintain the schema files from a tooling perspective 💪
=> chore: add jonaslagoni as maintainer

CODEOWNERS
I'm in to maintain our json schemas
https://github.com/asyncapi/spec-json-schemas/issues/513
=> chore: add Pakisan as maintainer

README.md
Changes were reverted (https://github.com/asyncapi/spec-json-schemas/pull/587)  but release was not
@derberg told that empty MR will fix this issue
https://github.com/asyncapi/spec-json-schemas/pull/587#issuecomment-3170706306
fyi: @fmvilas @derberg @jonaslagoni
=> feat: revert ROS2 release
