.github/workflows/automerge-release-pr-bump.yml
.github/workflows/release.yml
.npmrc.template
.travis.yml
README.md
package-lock.json
package.json

Same as https://github.com/asyncapi/generator/pull/242 except of:
- no docker release
- no contribution guide and pr template as this will be handled in https://github.com/asyncapi/asyncapi/issues/355
- added step to run `npm test`
- avoided mistakes done with generator - package marked as public and removed travis and updated readme
See also: https://github.com/asyncapi/parser-js/issues/52

feat: add configuration for automated releases

---

schemas/2.0.0.json

- According to specification message headers must be defined as a schema of an object. Other types are not allowed.
- Solution based on https://json-schema.org/understanding-json-schema/reference/combining.html#id5
now validation fails with:
```
"headers": {
"type": "integer",
"enum": [1, 2]
}
```
but it is allowing:
```
"headers": {
"type": "object",
"properties": {
"my-app-header": {
"type": "integer",
"minimum": 0,
"maximum": 100
}
}
}
```
Fixes https://github.com/asyncapi/parser-js/issues/68

fix: make sure header must be an object schema

---

.gitignore
schemas/2.0.0.json

- Schema should not enforce minProperties. Schema is not a spec but a tool that helps to work with spec, and should not add rules not described in the spec.
Resolves https://github.com/asyncapi/tck/issues/30

fix: Schema should not enforce minProperties

---

schemas/2.0.0.json

- Headers fix to enforce object
This is an issue that was supposed to be fixed already. I did those PRs in the past: https://github.com/asyncapi/asyncapi/pull/396/files and https://github.com/asyncapi/asyncapi-node/pull/10/files. As you can see the change to `asyncapi` repo was correct, but in the PR to `asyncapi-node` I made a mistake by leaving one ref 🤦

fix: Headers fix to enforce object

---

schemas/2.0.0.json

Fixes the definition of message examples. In practice, this is gonna create a breaking change in the parser so I suggest we introduce it as soon as possible in the recently released v1.0.0.
https://github.com/asyncapi/asyncapi/pull/453

fix: message examples definition

---

.github/workflows/bump.yml
package.json

- add new bump workflow
- add get package name script
- so far looks like the asyncapi/specs will be bumped only in the parser, which makes sense as parser is the only package that depends on it. Here PR to improve testing on parser https://github.com/asyncapi/parser-js/pull/213
Approve this first https://github.com/asyncapi/github-action-for-generator/pull/18
See also https://github.com/asyncapi/.github/issues/16

ci: add workflow that bumps asyncapi/specs in other asyncapi repos

---

.github/workflows/if-nodejs-pr-testing.yml
package-lock.json
package.json

- bump mocha and nyc dependencies to enable testing on windows. You will see the test is still failing but not because of nyc any more (https://github.com/asyncapi/asyncapi-node/pull/42/checks?check_run_id=1823359110). I'm not adding missing `lint` script as it is already added here https://github.com/asyncapi/asyncapi-node/pull/41
See also https://github.com/asyncapi/asyncapi-node/pull/41/checks?check_run_id=1823242727

chore: bump mocha and nyc dependencies to enable testing on windows

---

schemas/2.0.0.json

According to the specification the components object can be extended with specification extensions. This change realizes the specified behavior
Fixes #46

fix: allow extending components object with specification extensions

---

package-lock.json
package.json

see also https://github.com/asyncapi/spec/issues/536
it is supposed to work the same as here https://github.com/asyncapi/spec/pull/539 + npm release
relevant workflow configuration is in master already as it came from a global workflow https://github.com/asyncapi/asyncapi-node/commit/5c007ed02d2c625b001f6daa4a7827117a28a5ca

chore: enable releases for spec-related release branches

---

schemas/2.1.0.json

Split into separate commits to make it easier to review the addition I've
made to the schema. 
The first commit is just a copy of the 2.0.0.json file 
The second commit is the changes for SASL security schemes
The third commit updates the schema version
Contributes to: asyncapi/spec#466
Signed-off-by: Dale Lane <dale.lane@uk.ibm.com>

feat: add SASL mechanisms to the schema

---

schemas/2.0.0.json

As in title. As we support JSON Schema draft-07 as schema, then we should also support `true/false` schemas in JSON Schema of our spec. More info https://github.com/asyncapi/parser-js/issues/232
I removed `"type": "object",` from schema, because we should infer `type` field from `"http://json-schema.org/draft-07/schema#"`. Currently we override it.
See more https://github.com/asyncapi/parser-js/issues/232
Blocked by https://github.com/asyncapi/spec/pull/550

fix: support for Boolean JSON Schema

---

schemas/2.1.0.json

Added protocol constant that was defined in
https://github.com/asyncapi/bindings/pull/52
Contributes to: asyncapi/bindings#48
Signed-off-by: Dale Lane <dale.lane@uk.ibm.com>

feat: add new protocol bindings for IBM MQ

---

schemas/2.0.0.json

Complete message examples with `name` and `summary` attributes in order to:
* provide better documentation for examples,
* allow development of tooling leveraging examples (see Microcks.io)
This is implementing the [latest proposition](https://github.com/asyncapi/spec/issues/329#issuecomment-823993976) we had when discussing the topic. It does not introduce breaking changes and thus can be applied to current `2.0.0`.
This contributes to asyncapi/spec#329

feat: add name and summary properties to message examples

---

README.md
package.json

fixes https://github.com/asyncapi/spec-json-schemas/issues/45

chore: repo rename from asyncapi-node to spec-json-schemas

---

package.json

unfortunately, wildcards are still not supported and we need to always configure it for release, I just forgot about it

chore: configure prerelease for new release

---

schemas/1.0.0.json
schemas/1.1.0.json
schemas/1.2.0.json
schemas/2.0.0-rc1.json
schemas/2.0.0-rc2.json
schemas/2.0.0.json
schemas/2.1.0.json
schemas/2.2.0.json

> When a user visits a page served over HTTPS, their connection with the web server is encrypted with TLS and is therefore safeguarded from most sniffers and man-in-the-middle attacks. An HTTPS page that includes content fetched using cleartext HTTP is called a mixed content page. Pages like this are only partially encrypted, leaving the unencrypted content accessible to sniffers and man-in-the-middle attackers. That leaves the pages unsafe.
>
> Source: https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content
In consequence, most browsers block mixed content calls, meaning any request to `http://*` from a `https://*` website will be considered unsafe and blocked by the browser.
An example: https://github.com/asyncapi/studio/issues/146
Changing all schema …

fix: use HTTPS on $schema urls to avoid mixed content

---

schemas/1.0.0.json
schemas/1.1.0.json
schemas/1.2.0.json
schemas/2.0.0-rc1.json
schemas/2.0.0-rc2.json
schemas/2.0.0.json
schemas/2.1.0.json
schemas/2.2.0.json

Reverts asyncapi/spec-json-schemas#115
Tools like ajv (schema validator) are not compatible with https. See https://github.com/ajv-validator/ajv/issues/1104.
Also from a point of view of JSON Schema, this note about Schema ID's is very important:
> Even though schemas are identified by URIs, those identifiers are not necessarily network-addressable. They are just identifiers. Generally, implementations don’t make HTTP requests (https://) or read from the file system (file://) to fetch schemas. Instead, they provide a way to load schemas into an internal schema database. When a schema is referenced by it’s URI identifier, the schema is retrieved from the internal schema database.
Meaning it **should not** matter what protocol the URI has because It should not be treated as network address. …

fix: revert use HTTPS on $schema urls to avoid mixed content

---

go.mod
go.sum
spec-json-schemas.go
spec-json-schemas_test.go

Closes https://github.com/asyncapi/spec-json-schemas/issues/118
As side note, this is gonna be used by the https://github.com/asyncapi/parser-go to support all spec versions :)
PR will be created on https://github.com/asyncapi/parser-go right after merging this. You can see the change [here](https://github.com/asyncapi/parser-go/compare/master...smoya:feat/2.2.0?expand=1)

feat: add Go package

---

schemas/2.3.0.json

This adds Solace to the list of bindings.
The related PR on the spec itself is here: [asyncapi/spec#666](https://github.com/asyncapi/spec/pull/666)

feat: add Solace to the list of bindings.

---

schemas/2.0.0-rc1.json
schemas/2.0.0-rc2.json
schemas/2.0.0.json
schemas/2.1.0.json
schemas/2.2.0.json
schemas/2.3.0.json

This PR makes the regular expressions found in `pattern` and `patternProperties` fields unicode compliant (according to ECMA-262). It only changes the `2.3.0.json` schema but if you consider this should be applied to the rest, I can expand it.
It means now the regular expressions are compatible with `u` flag, flag that some JSON Schema parsers use when parsing a JSON Schema document. For example the one from Hyperjump](https://github.com/hyperjump-io/json-schema-validator). See implementation [here](https://github.com/hyperjump-io/json-schema-validator/blob/521818176d71d82344450a40a405fff2029e6bcc/lib/keywords/patternProperties.js) and [here}(https://github.com/hyperjump-io/json-schema-validator/blob/521818176d71d82344450a40a405fff2029e6bcc/lib/keywords/pattern.js). This …

fix: make pattern and patternProperties unicode ECMA-262 compliant

---

schemas/2.3.0.json

Force object type for message trait's headers.
Part of #82

fix: force object type for message trait's headers

---

CODEOWNERS

Adds @dalelane as code owner.
Closes https://github.com/asyncapi/spec/issues/720

chore: add Dale Lane as code owner

---

package.json

In order to allow CI to release pre-releases for `2022-04-release`, we need to merge this into `master` branch.
Part of https://github.com/asyncapi/spec/issues/735

chore: enable prereleases for 2022-04-release branch

---

.npmignore
README.md
go.mod

This change will make the Go module compatible with Go semantic versioning.
As the tag it is >= v2, Go requires `v2` suffix in module name. See https://golang.org/ref/mod#major-version-suffixes
I also took this opportunity to add few lines in the `README.md` explaining how to install and use the Go package.
The issue is that users won't be able to import the module ever due to the following error:
> invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

fix: add v2 suffix to Go module

---

schemas/2.4.0.json

2 passing (789ms)
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |     100 |      100 |     100 |     100 |                   
index.js |     100 |      100 |     100 |     100 |                   
----------|---------|----------|---------|---------|-------------------
Updates to include 'security' at operation and operationTrait level.
https://github.com/asyncapi/spec/pull/584

feat: security support added to operation and operationTrait 

---

package.json

This PR adds the [agreed-upon branch for next major spec version](https://github.com/asyncapi/spec/issues/734#issuecomment-1077455953) going forward.
Related to https://github.com/asyncapi/spec/issues/691

chore: add next major spec prerelease

---

schemas/2.4.0.json

Part of asyncapi/spec#717
This PR adds `serverVariables` as reusable objects to be used in `components`.
asyncapi/spec#717

feat: make server variables reuseable

---

.github/workflows/automerge-for-humans-add-ready-to-merge-or-do-not-merge-label.yml
.github/workflows/automerge-orphans.yml
.github/workflows/link-check-cron.yml
.github/workflows/link-check-pr.yml
package.json

This PR updates the next-major-spec branch with the upstream master changes.

chore: update with upstream master

---

index.js
package-lock.json
package.json
schemas/2.4.0.json

This PR is created upfront to reflect on a daily basis what things are included in the release.
Also, the reason to create this PR a long time before the release is to enable automation (bot keeps upstream branches always up to date with master, see this [action](https://github.com/asyncapi/spec/blob/master/.github/workflows/autoupdate.yml)) that we have in place to regularly update the release branch with whatever is changed in the master branch. So nobody has to do it manually.

feat: release for version 2.4.0 of the spec

---

bindings/amqp/channel.json
bindings/amqp/message.json
bindings/amqp/operation.json
bindings/anypointmq/channel.json
bindings/anypointmq/message.json
bindings/http/message.json
bindings/http/operation.json
bindings/ibmmq/channel.json
bindings/ibmmq/message.json
bindings/ibmmq/server.json
bindings/kafka/message.json
bindings/kafka/operation.json
bindings/mqtt/message.json
bindings/mqtt/operation.json
bindings/mqtt/server.json
bindings/nats/operation.json
bindings/solace/operation.json
bindings/solace/server.json
bindings/websockets/channel.json

This PR adds the JSON schema files from the bindings repository.
Things to figure out in this PR:
- Where should we place these files? 
- We could have them in `/bindings/protocol`, however, how do you reference specification extension? While they rarely, if ever change, using `https://raw.githubusercontent.com/asyncapi/asyncapi-node/v2.7.7/schemas/2.0.0.json#/definitions/specificationExtension` seems wrong in some sense, if it's part of spec v3 :thinking:
Things to figure out after this PR:
- How to version the binding schemas alongside spec schemas
**Related issues**
Partly solves https://github.com/asyncapi/bindings/issues/113

feat: add all protocol binding schemas

---

schemas/README.md
test/index.js

This PR adds a `README.md` file under `/schemas` directory so we can explain what's the preferable way for downloading/using AsyncAPI JSON Schema documents.
https://github.com/asyncapi/website/pull/680#issuecomment-1153700681

docs: explain how JSON Schema files are served

---

definitions/3.0.0/channelBindingsObject.json
definitions/3.0.0/channelItem.json
definitions/3.0.0/message.json
definitions/3.0.0/messageBindingsObject.json
definitions/3.0.0/messageTrait.json
definitions/3.0.0/operation.json
definitions/3.0.0/operationBindingsObject.json
definitions/3.0.0/operationTrait.json
definitions/3.0.0/server.json
definitions/3.0.0/serverBindingsObject.json

This PR adds 2 changes to the JSON Schema documents.
1. It fixes an issue where we allow all extensions regardless of the use of `x-`, which should not be allowed. Whether we want to propagate this across all versions, not so sure? 🤔  
2. It splits the generic `bindingsObject` into the 4 specific bindings for operation, channel, message, and server.
Related to https://github.com/asyncapi/spec/issues/507
Related to https://github.com/asyncapi/bindings/issues/113

feat: add specific binding schemas

---

index.js
schemas/all.schema-store.json
test/index.js

Partially fixes https://github.com/asyncapi/spec-json-schemas/issues/236, [pending a PR](https://github.com/SchemaStore/schemastore/compare/master...smoya:feat/asyncapiVersions?expand=1) on JSON Schema-Store repository.
This PR adds a new schema file that lists all JSON Schema files for all AsyncAPI spec versions. This is required for [Schema-Store](https://www.schemastore.org/) IDE plugins to support all versions.
https://github.com/asyncapi/spec-json-schemas/issues/236

feat: add schema listing all Schema-Store JSON Schema docs

---

README.md

- Resolves ISSUE_NUMBER #240
#240

docs: update readme.md with overview and custom validation sections

---

.github/workflows/if-nodejs-release.yml
.github/workflows/if-nodejs-version-bump.yml
.github/workflows/link-check-cron.yml
.github/workflows/stale-issues-prs.yml
README.md
package-lock.json
package.json
schemas/all.schema-store.json
test/index.js
tools/bundler/package-lock.json

This is PR is part of https://github.com/asyncapi/spec/issues/830 and updates `next-spec` branch with changes from `master`.

chore: update next-spec branch with master changes

---

definitions/2.5.0/serverVariables.json

Refs https://github.com/asyncapi/spec/issues/775
Refs https://github.com/asyncapi/spec/issues/830

feat: allow reusability of Server Variable Object

---

schemas/2.5.0.json

Add the Google Cloud Pub/Sub bindings _(`googlepubsub`)_ to the bindings list.
Bindings PR: https://github.com/asyncapi/bindings/pull/141
Spec PR: https://github.com/asyncapi/spec/pull/836

feat: add googlepubsub bindings

---

schemas/all.schema-store.json

Description
This PR adds missing AsyncAPI v2.5.0 schema to the all.schema-store.json doc.
cc @derberg

fix: add AsyncAPI v2.5.0 schema to the all.schema-store.json doc.

---

definitions/3.0.0/asyncapi.json
definitions/3.0.0/bindingsObject.json
definitions/3.0.0/channel.json
definitions/3.0.0/channelBindingsObject.json
definitions/3.0.0/channelMessages.json
definitions/3.0.0/messageBindingsObject.json
definitions/3.0.0/operation.json
definitions/3.0.0/operationTrait.json
definitions/3.0.0/operations.json
definitions/3.0.0/serverBindingsObject.json
schemas/3.0.0.json

It adds the new `operations` and `channels` objects for version 3.0.0.
https://github.com/asyncapi/spec/pull/827
https://github.com/asyncapi/spec/pull/806

feat!: add new channels and operations objects

---

index.d.ts

Used tsc command to recreate index.d.ts (definiton file) for index.js since it could not be compiled. The reason is that the index.js file is a commonjs file, and the definition file does not allow module augmentation with exports when commonjs is used to the main module.
Fixes #287

fix: generated index.d.ts file using tsc command (#287)

---

definitions/3.0.0/channel.json
definitions/3.0.0/operation.json
definitions/3.0.0/operationTrait.json
definitions/3.0.0/server.json

- add `title`, `summary` fields in `Server Object`,
- add `title`, `summary` fields in `Channel Object`,
- add `title` field in `Operation Object` and `Operation Trait Object`
Spec PR: https://github.com/asyncapi/spec/pull/796
Part of https://github.com/asyncapi/spec/pull/796

feat: add title, summary and description fields to the core models

---

definitions/3.0.0/channel.json

Channel's `servers` field allows references to the servers (not names).
Spec PR: https://github.com/asyncapi/spec/pull/852
Part of https://github.com/asyncapi/spec/pull/852

feat: channel's servers field allows references

---

definitions/3.0.0/server.json

Add `host` and `pathname` fields in server object.
Part of https://github.com/asyncapi/spec/pull/888

feat: add host and pathname fields in server object

---

test/schemas.js

This PR increases the timeout for the schema tests as we started to see spotted failed attempts in CI runs.

test: increase timeout that periodically fails

---

definitions/3.0.0/components.json

This PR fixes that it currently possible to define messages with oneOf in components when the spec clearly doesn't allow it.
Currently allowed, but should not:
```
components:
messages:
UserSignedUp:
oneOf:
- payload:
type: object
properties:
displayName:
type: string
description: Name of the user
email:
type: string
format: email
description: Email of the user
```
Fixes https://github.com/asyncapi/spec-json-schemas/issues/335

fix: oneOf should not be allowed in message components

---

definitions/2.0.0/message.json
definitions/2.1.0/message.json
definitions/2.2.0/message.json
definitions/2.3.0/message.json
definitions/2.4.0/message.json
definitions/2.5.0/message.json
definitions/2.6.0/message.json

This was initially added to v3 here: https://github.com/asyncapi/spec-json-schemas/pull/334
This PR replicates it for v2.

feat: add core message payload validation

---

README.md
go.mod

Caused by https://github.com/asyncapi/spec-json-schemas/issues/376
Go package module name was never updated, and it should be done every time a major version is released.
It is not ideal, but at this time there is no other choice. We will investigate further in https://github.com/asyncapi/spec-json-schemas/issues/376.
https://github.com/asyncapi/spec-json-schemas/issues/376

fix: go module version now supports v4

---

package.json

Related to: https://github.com/asyncapi/spec-json-schemas/pull/380
And all suddenly installation fails on windows 🤷🏼 https://github.com/asyncapi/spec-json-schemas/actions/runs/4798697556/jobs/8537525503 and current release is blocked
Followed https://github.com/asyncapi/.github/issues/205 instructions. Required topics added to repository
Once this PR is merged I will run a workflow in `.github` to update workflows.

ci: adjust release workflow to fix releases

---

README.md
schemas/2.0.0-without-$id.json
schemas/2.1.0-without-$id.json
schemas/2.2.0-without-$id.json
schemas/2.3.0-without-$id.json
schemas/2.4.0-without-$id.json
schemas/2.5.0-without-$id.json
schemas/2.6.0-without-$id.json
test/fixtures/asyncapi.yml
tools/bundler/index.js

autocompletion in IDEs is affected
some more rewriting in refs in the dedicated JSON Schema was needed
- `schemas` content is generated, you can skip review of this one
- added `test/fixtures/asyncapi.yml` to make it easier long term to test schemas on local, readme also updated
- main magic changes in `index.js`

fix: update references for avro and openapi schema

---

tools/bundler/index.js

This should fix all Sonarcloud code smells.

chore: unescape characters in regex + TODO since it is not required

---

definitions/3.0.0/multiFormatSchema.json
schemas/3.0.0-without-$id.json
schemas/3.0.0.json
test/docs/3.0.0/streetlights-all.json
test/docs/3.0.0/streetlights-avro.json
test/docs/3.0.0/streetlights-openapi.json

There was a bug where a multi-format schema wasn't supporting references to external documents. For example, the following schema was invalid:
```json
"ReferencedSchema" : {
"schemaFormat": "application/vnd.apache.avro;version=1.9.0",
"schema": {
"$ref": "reference-to-some-avro-file.avsc"
}
}
```
This PR fixes that by changing `schema` field to become `oneOf` either reference object or the schema (asyncapi, avro, etc).
https://asyncapi.slack.com/archives/C0230UAM6R3/p1689875953351089

fix: allow Reference objects in MultiFormat schema fields

---

definitions/3.0.0/parameter.json
test/docs/3.0.0/streetlights-all.json

This PR adapts the schemas to correctly validate the new simplified parameter object: https://www.asyncapi.com/docs/reference/specification/v3.0.0-next-major-spec.12#parameterObject
Fixes https://github.com/asyncapi/spec-json-schemas/issues/413
Related to https://github.com/asyncapi/spec/issues/583

feat: add new simplified parameter

---

bindings/googlepubsub/0.2.0/channel.json
bindings/googlepubsub/0.2.0/message.json
definitions/3.0.0/channelBindingsObject.json
definitions/3.0.0/messageBindingsObject.json

Adds support for `googlepubsub` bindings to v3 based on https://github.com/asyncapi/bindings/pull/213

feat: add googlepubsub bindings for v3

---

.npmignore

On a fresh install of the package `node_modules` in the `tools/bundler` are included while it's only useful when publishing the package.
This will allow to save some space / bandwith when installing this package.

chore: exclude tools/bundler/node_modules from final package

---

bindings/kafka/0.4.0/message.json

This PR fixes that the message.binding.kafka.key can be a reference.

fix: kafka key can be reference

---

bindings/googlepubsub/0.2.0/message.json
bindings/kafka/0.4.0/message.json
package-lock.json
tools/bundler/index.js
tools/bundler/package-lock.json

Remove trailing commas from some bindings.
Bundling was broken because of it. CI before did not indicate any issues because of Node version. Now package lock is at version 2 and we will use Node 16 instead of 14 - no more issue with CI, in future we will see errors

fix: remove trailing comma from kafka and googlepubsub bindings for messages

---

definitions/3.0.0/messageObject.json

https://github.com/asyncapi/spec-json-schemas/pull/370 introduced bug in Message Object JSON schema
`examples` `headers` and `payload` should not follow json schema spec
just like in [previous versions](https://github.com/asyncapi/spec-json-schemas/blob/next-major-spec/definitions/2.6.0/message.json#L118-L124) these fields need to be flexible as `payload` or `headers` are no necessarily json, could be avro for example
noticed with https://github.com/asyncapi/spec/blob/next-major-spec/examples/websocket-gemini.yml
I checked the change locally and works like a charm

fix: examples of messages should not follow json schema

---

definitions/3.0.0/messageObject.json
definitions/3.0.0/messageTrait.json
schemas/3.0.0-without-$id.json
schemas/3.0.0.json

Removes the `messageId` property from the Message and MessageTrait objects.
https://github.com/asyncapi/spec/issues/978

feat!: remove messageId from Message and MessageTrait objects

---

definitions/3.0.0/components.json

fix: add operations to the components section

---

definitions/3.0.0/channel.json
definitions/3.0.0/messageObject.json
definitions/3.0.0/messageTrait.json
definitions/3.0.0/operation.json
definitions/3.0.0/operationTrait.json
definitions/3.0.0/server.json

fixes: https://github.com/asyncapi/spec-json-schemas/issues/438
tested locally following https://github.com/asyncapi/spec-json-schemas/#schemastore-compatibility-testing and works like a charm

fix: enable `$ref` support for bindings

---

bindings/kafka/0.4.0/message.json

Kafka binding for messages, in 0.4 version introduced Avro support for `key` - but JSON Schema is not properly modified
Kafka message binding -> https://github.com/asyncapi/bindings/tree/master/kafka#message-binding-object
so things like below should be allowed:
```yaml
bindings:
kafka:
key:
$ref: "https://deploy-preview-921--asyncapi-website.netlify.app/resources/casestudies/adeo/CostingResponseKey.avsc"
```
Just go to https://studio.asyncapi.com/?url=https://raw.githubusercontent.com/asyncapi/spec/d78dcea70c9b094a3df72f9a4e811828cec778cc/examples/adeo-kafka-request-reply-asyncapi.yml and try to remove lines 242-245 all all suddenly validation stops failing
This is what json schema for message binding says: https://github.com/asyncapi/spec-json-schemas/blob/master/bindings/kafka/0.4.0/mes …

fix: make `key` in kafka msg binding validate as anyOf

---

scripts/validate-schemas.js

fix: reduced the complexity of validate-schema.js

---

bindings/http/0.3.0/message.json
bindings/http/0.3.0/operation.json
definitions/3.0.0/messageBindingsObject.json
definitions/3.0.0/operationBindingsObject.json

This PR adds the JSON Schema changes to the HTTP bindings introducing 0.3.0.
https://github.com/asyncapi/bindings/pull/235

feat: add HTTP 0.3.0 bindings

---

bindings/solace/0.2.0/operation.json
bindings/solace/0.3.0/operation.json
bindings/solace/0.4.0/operation.json
bindings/solace/0.4.0/server.json
definitions/3.0.0/operationBindingsObject.json
definitions/3.0.0/serverBindingsObject.json

- fix up solace bindings having a invalid schema
- feat: add per operation fields from: https://github.com/asyncapi/bindings/pull/237
**fix up solace bindings having a invalid schema**
To reproduce the bug, use this schema:
```yaml
components:
schemas:
Person:
type: string        
messages:
PersonEvent:
payload:
$ref: '#/components/schemas/Person'
schemaFormat: application/vnd.aai.asyncapi+json;version=2.0.0
contentType: application/json
operations:
addPerson:
action: send
channel:
$ref: '#/channels/address'
messages:
- $ref: '#/channels/address/messages/personEvent'
bindings:
solace:
bindingVersion: 0.3.0
destinations:
- destinationType: queue
queue:
name: CreatedHREvents
topicSubscriptions:
- person/*/created
- destinationType: queue
queue:
name: UpdatedHREvents …
```

feat:  solace add per operation fields

---

definitions/3.0.0/messageBindingsObject.json

Newest version of the http message bindings is `0.3.0`

fix: http message bindings not using latest version

---

definitions/3.0.0/operationBindingsObject.json
definitions/3.0.0/serverBindingsObject.json

Added missing versions to https://github.com/asyncapi/spec-json-schemas/pull/501
Added fix as per https://github.com/asyncapi/spec-json-schemas/pull/501#issuecomment-2028640789

fix: kafka bindings not using latest version

---

definitions/3.0.0/infoExtensions.json
extensions/linkedin/0.1.0/schema.json
schemas/3.0.0-without-$id.json
schemas/3.0.0.json

this pr add essential schemas to add support for linkedin extension
https://github.com/asyncapi/extensions-catalog/issues/78
cc: @derberg

feat: add linkedin extension support

---

definitions/3.0.0/messageExampleObject.json
definitions/3.0.0/messageObject.json
definitions/3.0.0/messageTrait.json
schemas/3.0.0-without-$id.json
schemas/3.0.0.json

This PR fixes that message trait examples are not validated correctly.
Fixes https://github.com/asyncapi/spec-json-schemas/issues/441

fix: add separate messsage example object

---

definitions/3.0.0/messageExampleObject.json

Define `payload` as `any` type
Fixes #560

fix: fix type of payload in MessageExample

---

bindings/sqs/0.2.0/channel.json
bindings/sqs/0.2.0/operation.json
bindings/sqs/0.3.0/channel.json
bindings/sqs/0.3.0/operation.json

According to [AWS documentation](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-delay-queues.html) the maximum amount of delay is 15 minutes and the property is set in seconds, therefore the maximum in the binding needs to be updated accordingly.

fix: maximum value for SQS `deliveryDelay` is 15 minutes, not 15 seconds
